#!/bin/bash
#set -euo pipefail

# COLORS
G='\033[1;32m'      # GREEN
R='\033[1;31m'      # RED
B='\033[0;33m'      # BLUE
P='\033[1;35m'      # PURPLE
O='\033[1;93m'      # ORANGE
D='\033[0m'         # DEFAULT

# THE PROJECT STAR HERE
clear
echo ""
echo -e "${R}██████╗░██╗░░░██╗  ██████╗░░█████╗░░█████╗░████████╗░█████╗░██████╗░  ░██████╗░█████╗░██╗░░░░░░█████╗░"
echo -e     "██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗  ██╔════╝██╔══██╗██║░░░░░██╔══██╗"
echo -e     "██████╦╝░╚████╔╝░  ██║░░██║██║░░██║██║░░╚═╝░░░██║░░░██║░░██║██████╔╝  ╚█████╗░██║░░██║██║░░░░░██║░░██║"
echo -e     "██╔══██╗░░╚██╔╝░░  ██║░░██║██║░░██║██║░░██╗░░░██║░░░██║░░██║██╔══██╗  ░╚═══██╗██║░░██║██║░░░░░██║░░██║"
echo -e     "██████╦╝░░░██║░░░  ██████╔╝╚█████╔╝╚█████╔╝░░░██║░░░╚█████╔╝██║░░██║  ██████╔╝╚█████╔╝███████╗╚█████╔╝"
echo -e     "╚═════╝░░░░╚═╝░░░  ╚═════╝░░╚════╝░░╚════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚═╝  ╚═════╝░░╚════╝░╚══════╝░╚════╝░${D}"
echo ""


for cmd in yt-dlp ffmpeg aria2c; do
    if !command -v $cmd &> /dev/null; then
        echo "Error: $cmd not found. Install it:"
        sudo pacman -S yt-dlp ffmpeg aria2
        exit 0
    fi
done

for cmd in yt-dlp ffmpeg aria2c; do
    if !command -v $cmd &> /dev/null; then
        echo "Program fail. Intall the dependencies"
        exit 1
    fi
done


# link here
read -p "Put here the link: " URL

if [ -z "$URL" ]; then
    echo "Link empity"
    exit 1
fi

echo "Start the downloading..."

yt-dlp \
    -f "bestvideo+bestaudio/best" \
    --merge-output-format mp4 \
    --downloader aria2c \
    --downloader-args "aria2c:-x 8 -s 8 -j 8 -k 1M" \
    --postprocessor-args "ffmpeg: -c:v libx264 -crf 18 -c:a aac" \
    -o "~/Downloads/%(title)s.%(ext)s" \
    "$URL"

echo "Download completed in ~/Downloads"